create table produtos (
id serial not null,
nome text not null,
categoria text not null,
preco float  not null
);


insert into 
	produtos(nome, categoria, preco)
values
('Smartphone Galaxy S21', 'Eletrônicos', 999.99),
('Camiseta Polo', 'Roupas', 39.99),
('Arroz Integral 1kg', 'Alimentos', 4.49),
('Shampoo Nutritivo', 'Cosméticos', 15.75),
('Laptop Dell XPS 13', 'Eletrônicos', 1499.99),
('Jeans Skinny Masculino', 'Roupas', 49.99),
('Maçã Fuji (1kg)', 'Alimentos', 2.99),
('Perfume Floral Elegante', 'Cosméticos', 55.50),
('Fritadeira Air Fryer', 'Eletrônicos', 249.99),
('Vestido de Festa', 'Roupas', 79.99),
('Azeite de Oliva Extra Virgem', 'Alimentos', 8.99),
('Kit de Maquiagem Profissional', 'Cosméticos', 29.99),
('Smartwatch Garmin Venu', 'Eletrônicos', 349.99),
('Tênis Esportivo', 'Roupas', 59.99),
('Cereal Matinal Integral', 'Alimentos', 3.99),
('Protetor Solar FPS 50', 'Cosméticos', 12.99),
('TV LED 55 Polegadas 4K', 'Eletrônicos', 799.99),
('Casaco de Inverno', 'Roupas', 89.99),
('Café Gourmet (250g)', 'Alimentos', 9.99),
('Kit de Cuidados com a Pele', 'Cosméticos', 38.99),
('Notebook HP Pavilion', 'Eletrônicos', 699.99),
('Sapato Social Masculino', 'Roupas', 99.99),
('Chocolate Amargo (100g)', 'Alimentos', 5.99),
('Condicionador Hidratante', 'Cosméticos', 22.99),
('Console de Videogame', 'Eletrônicos', 499.99),
('Saia Midi Estampada', 'Roupas', 69.99),
('Iogurte Natural (500g)', 'Alimentos', 2.49),
('Perfume Amadeirado Intenso', 'Cosméticos', 45.99),
('Forno Elétrico 30L', 'Eletrônicos', 179.99),
('Jaqueta Corta-Vento', 'Roupas', 59.99),
('Queijo Parmesão (150g)', 'Alimentos', 6.99),
('Kit de Pincéis de Maquiagem', 'Cosméticos', 19.99),
('Monitor Curvo 27 Polegadas', 'Eletrônicos', 349.99),
('Calça Jeans Skinny Feminina', 'Roupas', 49.99),
('Granola com Frutas Secas', 'Alimentos', 4.99),
('Loção Hidratante Corporal', 'Cosméticos', 14.99),
('Câmera Fotográfica DSLR', 'Eletrônicos', 899.99),
('Blusa de Tricô', 'Roupas', 34.99),
('Açúcar Mascavo (1kg)', 'Alimentos', 3.99),
('Batom Matte de Longa Duração', 'Cosméticos', 9.99),
('Aspirador de Pó Robô', 'Eletrônicos', 449.99),
('Bermuda Cargo Masculina', 'Roupas', 29.99),
('Chá Verde Orgânico', 'Alimentos', 7.99),
('Gel de Limpeza Facial', 'Cosméticos', 16.99),
('Cadeira Gamer Ergonômica', 'Eletrônicos', 329.99),
('Vestido Casual', 'Roupas', 44.99),
('Mel Puro (250g)', 'Alimentos', 10.99),
('Esmalte de Unhas', 'Cosméticos', 5.49),
('Impressora Multifuncional', 'Eletrônicos', 199.99),
('Boné Esportivo', 'Roupas', 19.99),
('Azeite de Coco Virgem', 'Alimentos', 12.99),
('Máscara Facial Revitalizante', 'Cosméticos', 8.99),
('Tablet Android', 'Eletrônicos', 299.99),
('Moletom com Capuz', 'Roupas', 54.99),
('Feijão Preto (1kg)', 'Alimentos', 3.49),
('Spray Fixador de Cabelo', 'Cosméticos', 13.99),
('Fone de Ouvido Bluetooth', 'Eletrônicos', 79.99),
('Calça Legging', 'Roupas', 24.99),
('Mix de Castanhas', 'Alimentos', 15.99),
('Gel de Banho Hidratante', 'Cosméticos', 7.49),
('Câmera de Segurança IP', 'Eletrônicos', 129.99),
('Jaqueta Jeans', 'Roupas', 64.99),
('Macarrão Integral (500g)', 'Alimentos', 2.79),
('Máscara de Cílios Volume', 'Cosméticos', 11.99),
('Console de Videogame Portátil', 'Eletrônicos', 169.99),
('Vestido de Verão Floral', 'Roupas', 49.99),
('Quinoa Orgânica (250g)', 'Alimentos', 6.99),
('Gloss Labial Hidratante', 'Cosméticos', 8.49),
('Notebook Lenovo ThinkPad', 'Eletrônicos', 799.99),
('Sapato Casual Feminino', 'Roupas', 74.99),
('Chocolate Ao Leite (100g)', 'Alimentos', 4.99),
('Condicionador Reparador', 'Cosméticos', 19.99),
('Console de Videogame Retro', 'Eletrônicos', 249.99),
('Vestido Longo de Festa', 'Roupas', 99.99),
('Iogurte Grego Natural (500g)', 'Alimentos', 3.99),
('Perfume Suave Floral', 'Cosméticos', 32.99),
('Forno Micro-ondas 20L', 'Eletrônicos', 129.99),
('Jaqueta de Couro', 'Roupas', 89.99),
('Queijo Gorgonzola (150g)', 'Alimentos', 8.99),
('Kit de Maquiagem para Olhos', 'Cosméticos', 22.99),
('Smart TV 50 Polegadas 4K', 'Eletrônicos', 499.99),
('Calça Jogger Masculina', 'Roupas', 39.99),
('Granola com Chocolate', 'Alimentos', 5.99),
('Loção Corporal Perfumada', 'Cosméticos', 17.99),
('Câmera de Ação 4K', 'Eletrônicos', 159.99),
('Blusa de Moletom', 'Roupas', 44.99),
('Açúcar de Coco (500g)', 'Alimentos', 6.99),
('Batom Hidratante', 'Cosméticos', 7.99),
('Robô de Limpeza Inteligente', 'Eletrônicos', 349.99),
('Bermuda Jeans Feminina', 'Roupas', 29.99),
('Chá de Ervas Relaxante', 'Alimentos', 4.99),
('Tônico Facial Revitalizante', 'Cosméticos', 14.99),
('Cadeira Ergonômica para Escritório', 'Eletrônicos', 239.99),
('Vestido Midi Estampado', 'Roupas', 54.99),
('Mel Silvestre (250g)', 'Alimentos', 9.99),
('Esmalte Cintilante', 'Cosméticos', 5.49),
('Impressora Laser Colorida', 'Eletrônicos', 299.99),
('Boné Casual', 'Roupas', 15.99),
('Azeite de Oliva Espanhol', 'Alimentos', 17.99),
('Máscara Facial Hidratante', 'Cosméticos', 9.49),
('Tablet iPad Pro', 'Eletrônicos', 899.99),
('Moletom com Zíper', 'Roupas', 69.99),
('Feijão Carioca (1kg)', 'Alimentos', 2.99),
('Spray de Fixação Forte', 'Cosméticos', 12.49),
('Fone de Ouvido com Cancelamento de Ruído', 'Eletrônicos', 129.99),
('Calça Legging Esportiva', 'Roupas', 29.99),
('Mix de Frutas Secas', 'Alimentos', 19.99),
('Gel de Banho Relaxante', 'Cosméticos', 8.99),
('Câmera de Segurança Externa', 'Eletrônicos', 179.99),
('Jaqueta Corta-Vento Esportiva', 'Roupas', 39.99),
('Macarrão de Arroz (500g)', 'Alimentos', 3.49),
('Máscara de Cílios Alongadora', 'Cosméticos', 11.99),
('Console de Videogame Retrô', 'Eletrônicos', 199.99),
('Vestido Casual Estampado', 'Roupas', 29.99),
('Quinoa Real Orgânica (250g)', 'Alimentos', 7.99),
('Gloss Labial Natural', 'Cosméticos', 6.49);




